/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_programacion_grupo5;

import javax.swing.JOptionPane;
import static proyecto_programacion_grupo5.BaseDatos.empleados;


/**
 *
 * @author Wilman
 */
public class CafeteriaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CafeteriaFrame.class.getName());

    /**
     * Creates new form CafeteriaFrame
     */
    public CafeteriaFrame() {
        
        BaseDatos.cargarEmpleados();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIdEmpleado1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonVerificar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonVolver1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonHoras = new javax.swing.JComboBox<>();
        BotonOpciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        BotonModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonIdEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIdEmpleado1ActionPerformed(evt);
            }
        });

        botonVerificar1.setText("Reservar Bebida");
        botonVerificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificar1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Sistema de reserva de bebidas");

        jLabel9.setText("Primero digitar ID del empleado");

        jLabel10.setText("NOTA*");

        jLabel11.setText("Solo una bebida por empleado.");

        botonVolver1.setText("Volver");
        botonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolver1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Porfavor digitar el ID del empleado ");

        jLabel1.setText("Horas de entrega");

        jLabel2.setText("Opciones bebidas");

        BotonHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9 AM", "2 PM", "10 PM" }));
        BotonHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHorasActionPerformed(evt);
            }
        });

        BotonOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Café", "Capuchino", "Capuchino con vainilla ", "Chocolate", "Moka ", "Te chai", "Café frio" }));
        BotonOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcionesActionPerformed(evt);
            }
        });

        jLabel3.setText("Primero digitar el ID del empleado");

        BotonModificar.setText("Modificar reserva");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        jButton1.setText("Listar pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolver1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonIdEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(180, 180, 180)
                                        .addComponent(BotonHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(140, 140, 140)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonVerificar1)
                                        .addGap(231, 231, 231)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(BotonModificar))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(BotonOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonVolver1)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonIdEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BotonOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BotonHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonVerificar1)
                                    .addComponent(BotonModificar))
                                .addGap(71, 71, 71)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIdEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIdEmpleado1ActionPerformed
        
        
    }//GEN-LAST:event_botonIdEmpleado1ActionPerformed

    private void botonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolver1ActionPerformed
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolver1ActionPerformed

    private void botonVerificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificar1ActionPerformed

        boolean confirmacion = false;
        boolean yaTiene = false;
        int empleado = 0;

        for (int i = 0; i < 6; i++) {

            String id = botonIdEmpleado1.getText();
            String idExtraida = Integer.toString(empleados[i].getId());

            if (id.equals(idExtraida)) {
                empleado = i;

                confirmacion = true;

            }

        }
        for (int i = 0; i < reservas.length; i++) {
            String id = botonIdEmpleado1.getText();
            String idExtraida = Integer.toString(empleados[i].getId());

            if (id.equals(idExtraida)) {
                if (reservas[empleado] != null) {
                    JOptionPane.showMessageDialog(null, "El empleado :" + reservas[empleado].getNombre() + " ya tiene una reserva");
                    yaTiene = true;
                }

                if (confirmacion == true && yaTiene == false) {
                    JOptionPane.showMessageDialog(null, "El empleado es: " + empleados[empleado].getNombre() + "\n" + "y reservo " + BotonOpciones.getSelectedItem() + " para ser entregado a las " + BotonHoras.getSelectedItem());
                    BaseDatos.reservarBebidas(reservas, empleados[empleado].getNombre(), BotonOpciones.getSelectedItem().toString(), BotonHoras.getSelectedItem().toString(), empleado);

                }
                
            }

        }
        if (confirmacion == false) {
            JOptionPane.showMessageDialog(null, "El empleado no existe");
        }
        



    }//GEN-LAST:event_botonVerificar1ActionPerformed

    private void BotonOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonOpcionesActionPerformed

    private void BotonHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonHorasActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        boolean yaTiene = true;
        boolean confirmacion = false;
        int empleado = 0;
        for (int i = 0; i < reservas.length; i++) {
            
            String id = botonIdEmpleado1.getText();
            String idExtraida = Integer.toString(empleados[i].getId());

            if (id.equals(idExtraida)) {

                if (reservas[i] == null) {
                    yaTiene = false;
                    empleado = i;
                    confirmacion=true;
                    JOptionPane.showMessageDialog(null, "El empleado " + empleados[empleado].getNombre() + " no tiene una reservacion");
                }

            }
        }
        for (int i = 0; i < reservas.length; i++) {
            String id = botonIdEmpleado1.getText();
            String idExtraida = Integer.toString(empleados[i].getId());

            if (id.equals(idExtraida)) {
                empleado=i;
                
                if (yaTiene == true) {
                    
                    reservas[empleado].setBebida(BotonOpciones.getSelectedItem().toString());
                    reservas[empleado].setHora(BotonHoras.getSelectedItem().toString());
                    JOptionPane.showMessageDialog(null, "Se modifico el pedido de: " + reservas[empleado].getNombre() + " por" + BotonOpciones.getSelectedItem().toString() + "y se entrega " + BotonHoras.getSelectedItem().toString());
                    confirmacion=true;
                }

            }

        }
        if (confirmacion==false) {
            JOptionPane.showMessageDialog(null, "El empleado no existe");
        }

    }//GEN-LAST:event_BotonModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String resultado="Estas son las reservas \n";
        for (int i = 0; i < reservas.length; i++) {
            if (reservas[i]!=null) {
                resultado+=reservas[i].getNombre()+"  ";
                resultado+=reservas[i].getBebida()+"  ";
                resultado+=reservas[i].getHora()+"  ";
                resultado+= "\n";
            }
        }
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CafeteriaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BotonHoras;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JComboBox<String> BotonOpciones;
    private javax.swing.JTextField botonIdEmpleado1;
    private javax.swing.JButton botonVerificar1;
    private javax.swing.JButton botonVolver1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
