/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_programacion_grupo5;

import javax.swing.JOptionPane;

/**
 *
 * @author elimm
 */
public class CineFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CineFrame.class.getName());

    /**
     * Creates new form CineFrame
     */
    public CineFrame() {
    initComponents();
    setTitle("Gestión de Cine");
    setLocationRelativeTo(null);
    
    BaseDatos.cargarDatos();
    cargarComboSalas();   // Llenar salas en el combo al abrir
    
}
    private void cargarComboSalas() {
    jComboBox1.removeAllItems();

    for (int i = 0; i < BaseDatos.totalSalas; i++) {
        Cine c = BaseDatos.salasCine[i];
        jComboBox1.addItem("Sala " + (i + 1) + " - " + c.pelicula + " (" + c.filas + "x" + c.columnas + ")");
    }

    if (BaseDatos.totalSalas > 0) {
        jComboBox1.setSelectedIndex(0);
        mostrarSala(0);
    }
}
    private void mostrarSala(int indice) {

    Cine sala = BaseDatos.salasCine[indice];

    String texto = "Película: " + sala.pelicula + "\n";
    texto += "Tamaño: " + sala.filas + "x" + sala.columnas + "\n\n";

    for (int i = 0; i < sala.filas; i++) {
        for (int j = 0; j < sala.columnas; j++) {
            int id = sala.getID(i, j);
            if (id == 0) {
                texto += "[  ] ";
            } else {
                texto += "[" + id + "] ";
            }
        }
        texto += "\n";
    }

    jTextArea1.setText(texto);
}


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestión de Cine");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setActionCommand("jComboSalas");

        jButton1.setText("Ver salas");
        jButton1.setActionCommand("btnVer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Reservar");
        jButton2.setActionCommand("btnReservar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Liberar");
        jButton3.setActionCommand("btnLiberar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cambiar pelicula");
        jButton4.setToolTipText("");
        jButton4.setActionCommand("btnCambiarPel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cambiar Tamaño");
        jButton5.setActionCommand("btnCambiarTam");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Volver");
        jButton6.setActionCommand("btnVolver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int idx = jComboBox1.getSelectedIndex();

        String nueva = JOptionPane.showInputDialog("Nueva película:");
        if (nueva != null && !nueva.isBlank()) {
            BaseDatos.salasCine[idx].setPelicula(nueva);
            cargarComboSalas();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int idx = jComboBox1.getSelectedIndex();
        if (idx >= 0) {
        mostrarSala(idx);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int idx = jComboBox1.getSelectedIndex();
        Cine sala = BaseDatos.salasCine[idx];

        try {
            int fila = Integer.parseInt(JOptionPane.showInputDialog("Fila:")) - 1;
            int col = Integer.parseInt(JOptionPane.showInputDialog("Columna:")) - 1;
            int id = Integer.parseInt(JOptionPane.showInputDialog("ID del empleado:"));
            
            boolean existe = false;
            for (int i = 0; i < BaseDatos.totalEmpleados; i++) {
                if (BaseDatos.empleados[i].id == id) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                JOptionPane.showMessageDialog(this, "Empleado no existe");
                return;
            }
            boolean ok = sala.reservar(fila, col, id);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Reservado correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Asiento ocupado");
            }

            mostrarSala(idx);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Entrada inválida");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int idx = jComboBox1.getSelectedIndex();
        Cine sala = BaseDatos.salasCine[idx];

    try {
        int fila = Integer.parseInt(JOptionPane.showInputDialog("Fila:")) - 1;
        int col = Integer.parseInt(JOptionPane.showInputDialog("Columna:")) - 1;

        boolean ok = sala.liberar(fila, col);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Asiento liberado");
        } else {
            JOptionPane.showMessageDialog(this, "El asiento ya estaba libre");
        }

        mostrarSala(idx);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida");
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int idx = jComboBox1.getSelectedIndex();

        Object[] opciones = {"25 (5x5)", "30 (5x6)"};

        int sel = JOptionPane.showOptionDialog(
            this,
            "Seleccione el tamaño de la sala:",
            "Cambiar tamaño",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (sel == 0) {
            BaseDatos.salasCine[idx].setTamaño(5, 5);
        } else if (sel == 1) {
            BaseDatos.salasCine[idx].setTamaño(5, 6);
        }

cargarComboSalas();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CineFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
