/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_programacion_grupo5;

import javax.swing.JOptionPane;

/**
 *
 * @author elimm
 */
public class ClasesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClasesFrame.class.getName());

    /**
     * Creates new form ClasesFrame
     */
    public ClasesFrame() {
        initComponents();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Baile");
        jComboBox1.addItem("Yoga");
        jComboBox2.removeAllItems();
        jComboBox2.addItem("7pm");
        jComboBox2.addItem("8pm");


    }
    
    private ClaseActividades getClaseSeleccionada() {

        int actividad = jComboBox1.getSelectedIndex(); // 0 = Baile, 1 = Yoga
        int horario = jComboBox2.getSelectedIndex();   // 0 = 7pm, 1 = 8pm

        if (actividad == 0) {
        // Baile
            return BaseDatos.salabaile[horario];
        } else {
        // Yoga
            return BaseDatos.salayoga[horario];
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a las clases de yoga y baile");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setActionCommand("jComboClase");
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 113, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setActionCommand("jComboHorario");
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1.setText("Ver clase");
        jButton1.setActionCommand("btnVer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 145, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 183, 240, 221));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton2.setText("Reservar");
        jButton2.setActionCommand("btnReservar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 183, 131, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setText("Liberar");
        jButton3.setActionCommand("btnLiberar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 215, 131, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton4.setText("Cambiar de Profesor");
        jButton4.setActionCommand("btnProfesor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 253, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton5.setText("Volver");
        jButton5.setActionCommand("btnVolver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 285, 131, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("¿Desearia inscribirse a una clase?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 39, 233, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clases menu.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -70, 560, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClaseActividades clase = getClaseSeleccionada();

        String texto = "Clase: " + clase.nombre + "\n";
        texto += "Profesor: " + clase.profesor + "\n\n";
    

        jTextArea1.setText(texto);

        for (int i = 0; i < 30; i++) {
            if (clase.cupos[i] == 0) {
                texto += "[" + (i+1) + "] Libre\n";
            } else {
                texto += "[" + (i+1) + "] Ocupado por ID " + clase.cupos[i] + "\n";
            }
        }

        jTextArea1.setText(texto);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClaseActividades clase = getClaseSeleccionada();

        String idStr = JOptionPane.showInputDialog(this, "Ingrese ID del empleado:");
        if (idStr == null) 
            return;

        int id = Integer.parseInt(idStr);

        boolean ok = clase.reservar(id);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Empleado ha reservado un cupo de la clase!");
        } else {
            JOptionPane.showMessageDialog(this, "No hay espacios disponibles.", "Error", 0);
        }

        jButton1ActionPerformed(null); // refrescar
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ClaseActividades clase = getClaseSeleccionada();

        String idStr = JOptionPane.showInputDialog(this, "Ingrese ID a eliminar:");
        if (idStr == null) 
            return;

        int id = Integer.parseInt(idStr);

        boolean ok = clase.liberar(id);

        if (ok) {
            JOptionPane.showMessageDialog(this, "Empleado ha liberado un cupo de la clase.");
        } else {
            JOptionPane.showMessageDialog(this, "Ese empleado no está inscrito.", "Error", 0);
            }
    
        jButton1ActionPerformed(null); // refrescar
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Obtener la clase seleccionada (usa el método que ya tenemos)
        ClaseActividades clase = getClaseSeleccionada();
        if (clase == null) {
            JOptionPane.showMessageDialog(this, "No hay clase seleccionada.");
            return;
        }

        // Pedir nuevo profesor
        String nuevo = JOptionPane.showInputDialog(this, "Nombre del nuevo profesor:", clase.profesor);
        if (nuevo == null) return; // usuario canceló

        nuevo = nuevo.trim();
        if (nuevo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre inválido.");
            return;
        }

        // Actualizar y confirmar
        clase.profesor = nuevo;
        JOptionPane.showMessageDialog(this, "Profesor actualizado a: " + nuevo);
        jButton1ActionPerformed(null); // refrescar
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClasesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
